package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ---------------------------------------------------------------------------
// Systemd unit parser
// ---------------------------------------------------------------------------

// systemdUnit holds the fields we extract from a .service file.
// We only care about what's needed to generate a cogovinit .toml config.
type systemdUnit struct {
	description string
	execStart   string
	restart     string // systemd vocabulary: "always", "on-failure", "no", ""
}

// parseSystemdUnit reads a systemd .service file and extracts relevant fields.
// It handles [Section] headers, inline comments, and line continuations.
// Unknown keys are silently ignored — we don't need them.
func parseSystemdUnit(path string) (systemdUnit, error) {
	f, err := os.Open(path)
	if err != nil {
		return systemdUnit{}, fmt.Errorf("cannot open unit file %s: %v", path, err)
	}
	defer f.Close()

	var unit systemdUnit
	scanner := bufio.NewScanner(f)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip blank lines, comments, and section headers
		if line == "" || strings.HasPrefix(line, "#") ||
			strings.HasPrefix(line, ";") || strings.HasPrefix(line, "[") {
			continue
		}

		idx := strings.IndexByte(line, '=')
		if idx < 0 {
			continue
		}

		key := strings.TrimSpace(line[:idx])
		val := strings.TrimSpace(line[idx+1:])

		switch key {
		case "Description":
			unit.description = val
		case "ExecStart":
			// Strip systemd exec-start prefixes:
			// "-" = ignore failure, "@" = argv[0] override,
			// "+" = full privileges, "!" = no-new-privileges
			unit.execStart = strings.TrimLeft(val, "-@+!")
		case "Restart":
			unit.restart = val
		}
	}

	if err := scanner.Err(); err != nil {
		return systemdUnit{}, fmt.Errorf("error reading unit file %s: %v", path, err)
	}

	return unit, nil
}

// mapRestart translates systemd Restart= vocabulary to cogovinit vocabulary.
// cogovinit understands: "always", "on-failure", "no"
func mapRestart(systemdRestart string) string {
	switch systemdRestart {
	case "always", "on-success", "on-abnormal", "on-watchdog", "on-abort":
		return "always"
	case "on-failure":
		return "on-failure"
	default:
		// "no", "" or anything unknown → don't restart
		return "no"
	}
}

// rewriteBinaryPath rewrites the binary (first token of ExecStart) so that
// absolute paths under /usr, /bin, /sbin point into AurTargetPrefix.
//
// We only rewrite the binary, not the arguments — argument paths
// (config files, data dirs) typically live on the host and should be
// left as-is. The daemon will find its own files through the rewritten
// binary's rpath which already covers AurTargetPrefix (set by patchelf).
//
// Example:
//   "/usr/bin/myapp --config /etc/myapp.conf"
//   → "<AurTargetPrefix>/usr/bin/myapp --config /etc/myapp.conf"
func rewriteBinaryPath(execStart string) string {
	if execStart == "" {
		return execStart
	}

	// Split off the binary from the rest
	spaceIdx := strings.IndexByte(execStart, ' ')
	var binary, rest string
	if spaceIdx < 0 {
		binary = execStart
		rest = ""
	} else {
		binary = execStart[:spaceIdx]
		rest = execStart[spaceIdx:] // preserves the leading space
	}

	for _, prefix := range []string{"/usr/", "/bin/", "/sbin/"} {
		if strings.HasPrefix(binary, prefix) {
			// Strip the leading "/" so filepath.Join works correctly
			relative := strings.TrimPrefix(binary, "/")
			binary = filepath.Join(AurTargetPrefix, relative)
			break
		}
	}

	return binary + rest
}

// generateCogovinitToml produces the .toml config content for cogovinit.
// The format matches what cogovinit's serde/toml parser expects.
func generateCogovinitToml(
	serviceName string,
	pkgName string,
	sourceUnit string,
	unit systemdUnit,
) string {
	desc := unit.description
	if desc == "" {
		desc = fmt.Sprintf("%s service (auto-converted from systemd unit by pbb)", pkgName)
	}

	restart := mapRestart(unit.restart)
	execStart := rewriteBinaryPath(unit.execStart)

	// Sandbox HOME path — cogovinit will create this directory before exec
	sandboxHome := filepath.Join(os.TempDir(), "pbb-sandbox-"+serviceName)

	return fmt.Sprintf(
		"# cogovinit service configuration\n"+
			"# Auto-generated by pbb -S-AUR %s\n"+
			"# Source systemd unit: %s\n"+
			"# DO NOT EDIT the ExecStart path manually — it is managed by pbb\n\n"+
			"[service]\n"+
			"name        = %q\n"+
			"description = %q\n"+
			"exec_start  = %q\n"+
			"restart     = %q\n"+
			"restart_delay_secs = 3\n\n"+
			"[sandbox]\n"+
			"isolated        = true\n"+
			"restrict_home   = true\n"+
			"sandbox_home    = %q\n",
		pkgName,
		sourceUnit,
		serviceName,
		desc,
		execStart,
		restart,
		sandboxHome,
	)
}

// interceptAndRegisterServices scans pkgDir for systemd unit files under
// usr/lib/systemd/system/*.service, converts each one to a cogovinit .toml,
// and saves the result to InitdDir.
//
// Called inside case "-S-AUR" in main.go just before pkgDir is removed.
// Non-fatal: errors are printed as warnings so the package install still succeeds.
func interceptAndRegisterServices(pkgName string, pkgDir string) {
	systemdDir := filepath.Join(pkgDir, "usr", "lib", "systemd", "system")

	entries, err := os.ReadDir(systemdDir)
	if err != nil {
		// No systemd units — completely normal for most AUR packages
		if verbose {
			fmt.Printf("[v] No systemd units in '%s' (%s not found)\n", pkgName, systemdDir)
		}
		return
	}

	converted := 0

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".service") {
			continue
		}

		unitPath := filepath.Join(systemdDir, entry.Name())
		unit, err := parseSystemdUnit(unitPath)
		if err != nil {
			fmt.Printf("[pbb-init] Warning: failed to parse %s: %v\n", entry.Name(), err)
			continue
		}

		if unit.execStart == "" {
			if verbose {
				fmt.Printf("[v] Skipping %s — no ExecStart field\n", entry.Name())
			}
			continue
		}

		// "foo.service" -> "foo"
		serviceName := strings.TrimSuffix(entry.Name(), ".service")

		tomlContent := generateCogovinitToml(serviceName, pkgName, unitPath, unit)

		confPath := filepath.Join(InitdDir, serviceName+".toml")
		if err := os.WriteFile(confPath, []byte(tomlContent), 0644); err != nil {
			fmt.Printf("[pbb-init] Warning: failed to write config for '%s': %v\n", serviceName, err)
			continue
		}

		fmt.Printf("[pbb-init] Registered service '%s'\n          config: %s\n", serviceName, confPath)
		converted++
	}

	if converted > 0 {
		fmt.Printf("[pbb-init] %d service(s) registered for cogovinit.\n", converted)
		fmt.Printf("           Start with: cogovinit start %s\n", pkgName)
	}
}
